openapi: 3.0.3
info:
  title: ''
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/user/signup:
    post:
      summary: ''
      operationId: postApiUserSignup
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/users/login:
    post:
      summary: ''
      operationId: postApiUsersLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
